export type MediaKind = 'image' | 'audio' | 'video';

export type FormatInfo = {
  kind: MediaKind;
  label: string;
};

// Keys are the format ids used everywhere else (router, presets, capability tables).
export const FORMATS: Record<string, FormatInfo> = {
  jpeg: { kind: 'image', label: 'JPEG image' },
  png: { kind: 'image', label: 'PNG image' },
  apng: { kind: 'image', label: 'Animated PNG' },
  gif: { kind: 'image', label: 'GIF image' },
  webp: { kind: 'image', label: 'WebP image' },
  avif: { kind: 'image', label: 'AVIF image' },
  heic: { kind: 'image', label: 'HEIC image' },
  jxl: { kind: 'image', label: 'JPEG XL image' },
  bmp: { kind: 'image', label: 'BMP image' },
  svg: { kind: 'image', label: 'SVG image' },
  ico: { kind: 'image', label: 'Icon' },
  cur: { kind: 'image', label: 'Cursor' },
  icns: { kind: 'image', label: 'macOS icon' },
  tiff: { kind: 'image', label: 'TIFF image' },
  psd: { kind: 'image', label: 'Photoshop document' },
  exr: { kind: 'image', label: 'OpenEXR image' },
  hdr: { kind: 'image', label: 'Radiance HDR image' },
  jp2: { kind: 'image', label: 'JPEG 2000 image' },
  dds: { kind: 'image', label: 'DDS texture' },
  tga: { kind: 'image', label: 'TGA image' },
  pcx: { kind: 'image', label: 'PCX image' },
  pnm: { kind: 'image', label: 'Netpbm image' },
  xbm: { kind: 'image', label: 'X bitmap' },
  xpm: { kind: 'image', label: 'X pixmap' },
  sgi: { kind: 'image', label: 'SGI image' },
  sun: { kind: 'image', label: 'Sun Raster image' },
  wbmp: { kind: 'image', label: 'Wireless bitmap' },
  qoi: { kind: 'image', label: 'QOI image' },
  fits: { kind: 'image', label: 'FITS image' },
  dng: { kind: 'image', label: 'DNG raw photo' },
  cr2: { kind: 'image', label: 'Canon raw photo' },
  cr3: { kind: 'image', label: 'Canon raw photo' },
  nef: { kind: 'image', label: 'Nikon raw photo' },
  arw: { kind: 'image', label: 'Sony raw photo' },
  orf: { kind: 'image', label: 'Olympus raw photo' },
  rw2: { kind: 'image', label: 'Panasonic raw photo' },
  raf: { kind: 'image', label: 'Fujifilm raw photo' },
  pef: { kind: 'image', label: 'Pentax raw photo' },
  srw: { kind: 'image', label: 'Samsung raw photo' },

  mp3: { kind: 'audio', label: 'MP3 audio' },
  aac: { kind: 'audio', label: 'AAC audio' },
  m4a: { kind: 'audio', label: 'M4A audio' },
  m4b: { kind: 'audio', label: 'Audiobook' },
  wav: { kind: 'audio', label: 'WAV audio' },
  flac: { kind: 'audio', label: 'FLAC audio' },
  ogg: { kind: 'audio', label: 'Ogg audio' },
  opus: { kind: 'audio', label: 'Opus audio' },
  wma: { kind: 'audio', label: 'WMA audio' },
  aiff: { kind: 'audio', label: 'AIFF audio' },
  wv: { kind: 'audio', label: 'WavPack audio' },
  ape: { kind: 'audio', label: "Monkey's Audio" },
  tta: { kind: 'audio', label: 'TTA audio' },
  tak: { kind: 'audio', label: 'TAK audio' },
  dsf: { kind: 'audio', label: 'DSD audio' },
  dff: { kind: 'audio', label: 'DSD audio' },
  rf64: { kind: 'audio', label: 'RF64 audio' },
  w64: { kind: 'audio', label: 'Wave64 audio' },
  caf: { kind: 'audio', label: 'Core Audio file' },
  ac3: { kind: 'audio', label: 'AC-3 audio' },
  dts: { kind: 'audio', label: 'DTS audio' },
  amr: { kind: 'audio', label: 'AMR voice recording' },
  spx: { kind: 'audio', label: 'Speex audio' },
  mpc: { kind: 'audio', label: 'Musepack audio' },
  au: { kind: 'audio', label: 'AU audio' },
  voc: { kind: 'audio', label: 'VOC audio' },
  ra: { kind: 'audio', label: 'RealAudio' },
  gsm: { kind: 'audio', label: 'GSM audio' },

  mp4: { kind: 'video', label: 'MP4 video' },
  m4v: { kind: 'video', label: 'M4V video' },
  mov: { kind: 'video', label: 'QuickTime video' },
  mkv: { kind: 'video', label: 'Matroska video' },
  webm: { kind: 'video', label: 'WebM video' },
  avi: { kind: 'video', label: 'AVI video' },
  wmv: { kind: 'video', label: 'WMV video' },
  mts: { kind: 'video', label: 'MPEG-TS video' },
  mpg: { kind: 'video', label: 'MPEG video' },
  mxf: { kind: 'video', label: 'MXF video' },
  dv: { kind: 'video', label: 'DV video' },
  '3gp': { kind: 'video', label: '3GP video' },
  flv: { kind: 'video', label: 'Flash video' },
  rm: { kind: 'video', label: 'RealMedia video' },
  ogv: { kind: 'video', label: 'Ogg video' },
  nut: { kind: 'video', label: 'NUT video' },
};

export function formatInfo(format: string): FormatInfo | undefined {
  return FORMATS[format];
}
